version: '3.7'

services:
  my_websockets_app:
    build: .
    stdin_open: true
    tty: true
    ports:
      - "8765:8765"
    env_file:
      - .env
    environment:
        REDIS_PASSWORD: ${REDIS_PASSWORD}
        REDIS_PORT: ${REDIS_PORT}
        REDIS_HOST: ${REDIS_HOST}
    networks:
      - backend
  
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
    networks:
      - backend

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
    networks:
      - backend

networks:
  backend:

volumes:
  mongodb:
  static:
  cache:
    driver: local

